# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 407)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 18, 51, 21))
        self.comboBox.setObjectName("comboBox")
        self.label_selectdevice = QtWidgets.QLabel(self.centralwidget)
        self.label_selectdevice.setGeometry(QtCore.QRect(50, 20, 81, 16))
        self.label_selectdevice.setObjectName("label_selectdevice")
        self.pushButton_selectPcPath = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectPcPath.setGeometry(QtCore.QRect(160, 60, 121, 28))
        self.pushButton_selectPcPath.setObjectName("pushButton_selectPcPath")
        self.pushButton_selectDevicePath = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectDevicePath.setGeometry(QtCore.QRect(160, 100, 121, 28))
        self.pushButton_selectDevicePath.setObjectName("pushButton_selectDevicePath")
        self.label_isComputerFolderSelected = QtWidgets.QLabel(self.centralwidget)
        self.label_isComputerFolderSelected.setGeometry(QtCore.QRect(50, 66, 81, 16))
        self.label_isComputerFolderSelected.setObjectName("label_isComputerFolderSelected")
        self.label_isDeviceFolderSelected = QtWidgets.QLabel(self.centralwidget)
        self.label_isDeviceFolderSelected.setGeometry(QtCore.QRect(50, 106, 81, 16))
        self.label_isDeviceFolderSelected.setObjectName("label_isDeviceFolderSelected")
        self.groupBox_leader = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_leader.setGeometry(QtCore.QRect(50, 150, 241, 61))
        self.groupBox_leader.setObjectName("groupBox_leader")
        self.radioButton_deviceLeader = QtWidgets.QRadioButton(self.groupBox_leader)
        self.radioButton_deviceLeader.setGeometry(QtCore.QRect(121, 27, 111, 20))
        self.radioButton_deviceLeader.setChecked(False)
        self.radioButton_deviceLeader.setObjectName("radioButton_deviceLeader")
        self.radioButton_PcLeader = QtWidgets.QRadioButton(self.groupBox_leader)
        self.radioButton_PcLeader.setGeometry(QtCore.QRect(16, 27, 95, 20))
        self.radioButton_PcLeader.setChecked(True)
        self.radioButton_PcLeader.setObjectName("radioButton_PcLeader")
        self.groupBox_permissions = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_permissions.setGeometry(QtCore.QRect(50, 230, 241, 91))
        self.groupBox_permissions.setObjectName("groupBox_permissions")
        self.checkBox_deleteOldFiles = QtWidgets.QCheckBox(self.groupBox_permissions)
        self.checkBox_deleteOldFiles.setGeometry(QtCore.QRect(20, 25, 191, 20))
        self.checkBox_deleteOldFiles.setChecked(True)
        self.checkBox_deleteOldFiles.setObjectName("checkBox_deleteOldFiles")
        self.checkBox_copyNewFiles = QtWidgets.QCheckBox(self.groupBox_permissions)
        self.checkBox_copyNewFiles.setGeometry(QtCore.QRect(20, 50, 191, 20))
        self.checkBox_copyNewFiles.setChecked(True)
        self.checkBox_copyNewFiles.setObjectName("checkBox_copyNewFiles")
        self.pushButton_sync = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sync.setGeometry(QtCore.QRect(410, 330, 93, 28))
        self.pushButton_sync.setObjectName("pushButton_sync")
        self.pushButton_clearPcFolder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clearPcFolder.setGeometry(QtCore.QRect(290, 60, 51, 28))
        self.pushButton_clearPcFolder.setObjectName("pushButton_clearPcFolder")
        self.pushButton_clearDeviceFolder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clearDeviceFolder.setGeometry(QtCore.QRect(290, 100, 51, 28))
        self.pushButton_clearDeviceFolder.setObjectName("pushButton_clearDeviceFolder")
        self.pushButton_saveSettings = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_saveSettings.setGeometry(QtCore.QRect(50, 330, 93, 28))
        self.pushButton_saveSettings.setObjectName("pushButton_saveSettings")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_selectPcPath, self.pushButton_selectDevicePath)
        MainWindow.setTabOrder(self.pushButton_selectDevicePath, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.radioButton_PcLeader)
        MainWindow.setTabOrder(self.radioButton_PcLeader, self.radioButton_deviceLeader)
        MainWindow.setTabOrder(self.radioButton_deviceLeader, self.checkBox_deleteOldFiles)
        MainWindow.setTabOrder(self.checkBox_deleteOldFiles, self.checkBox_copyNewFiles)
        MainWindow.setTabOrder(self.checkBox_copyNewFiles, self.pushButton_sync)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_selectdevice.setText(_translate("MainWindow", "Select device:"))
        self.pushButton_selectPcPath.setText(_translate("MainWindow", "Computer folder"))
        self.pushButton_selectDevicePath.setText(_translate("MainWindow", "Device folder"))
        self.label_isComputerFolderSelected.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00aa00;\">Selected!</span></p></body></html>"))
        self.label_isDeviceFolderSelected.setText(_translate("MainWindow", "<span style=\" color:#aa0000;\">Not selected!</span>"))
        self.groupBox_leader.setTitle(_translate("MainWindow", "Select leader*:"))
        self.radioButton_deviceLeader.setText(_translate("MainWindow", "Extern. device"))
        self.radioButton_PcLeader.setText(_translate("MainWindow", "Computer"))
        self.groupBox_permissions.setTitle(_translate("MainWindow", "Permissions:"))
        self.checkBox_deleteOldFiles.setText(_translate("MainWindow", "Allow to delete old files"))
        self.checkBox_copyNewFiles.setText(_translate("MainWindow", "Allow to copy new files"))
        self.pushButton_sync.setText(_translate("MainWindow", "Sync"))
        self.pushButton_clearPcFolder.setText(_translate("MainWindow", "Clear"))
        self.pushButton_clearDeviceFolder.setText(_translate("MainWindow", "Clear"))
        self.pushButton_saveSettings.setText(_translate("MainWindow", "Save settings"))

